config/routes.rb
Rails.application.routes.draw do
  resources :users, param: :email, constraints: { email: /[^\/]+/ }, defaults: { format: :json } do
    resources :time_messages, only: [:index, :show, :create, :update, :destroy], defaults: { format: :json }
  end

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/time_message.rb
class TimeMessage < ApplicationRecord
  belongs_to :user, foreign_key: :user_email, primary_key: :email
  validates :content, presence: true
  validates :date_to_open, presence: true
  validates :user_email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    has_many :time_messages, foreign_key: :user_email, primary_key: :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/time_messages_controller.rb
# app/controllers/time_messages_controller.rb
class TimeMessagesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_user
  before_action :set_time_message, only: %i[ show edit update destroy ]

  # GET /users/:email/time_messages
  def index
    @time_messages = @user.time_messages.where("date_to_open <= ?", Date.today)
    render json: @time_messages
  end

  # GET /users/:email/time_messages/:id
  def show
    @time_message = TimeMessage.find(params[:id])
    render json: @time_message
  end

  # POST /users/:email/time_messages
  def create
    @time_message = TimeMessage.new(time_message_params)
    @time_message.date_to_open = Date.parse(time_message_params[:date_to_open])

    if @time_message.save
      render json: @time_message, status: :created
    else
      render json: @time_message.errors, status: :unprocessable_entity
    end
  end

  # PUT /users/:email/time_messages/:id
  def update
    if @time_message.update(time_message_params)
      render json: @time_message, status: :ok
    else
      render json: @time_message.errors, status: :unprocessable_entity
    end
  end

  # DELETE /users/:email/time_messages/:id
  def destroy
    @time_message.destroy!
    render json: @time_message
  end

  private
  def set_user
    Rails.logger.info "Params received: #{params.inspect}"
    @user = User.find_by(email: params[:user_email])
    unless @user
      render json: { error: "User not found" }, status: :not_found
    end
  end

  def set_time_message
    @time_message = @user.time_messages.find(params[:id])
  end

  def time_message_params
    params.require(:time_message).permit(:content, :date_to_open).merge(user_email: params[:user_email])
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.json { render :show, status: :created, location: @user }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.json { render :show, status: :ok, location: @user }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by(email: params[:email])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_messages_helper.rb
module TimeMessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeCapsule</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/time_messages/_form.html.erb
<%= form_with(model: time_message) do |form| %>
  <% if time_message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(time_message.errors.count, "error") %> prohibited this time_message from being saved:</h2>

      <ul>
        <% time_message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.label :dateToOpen, style: "display: block" %>
    <%= form.datetime_field :dateToOpen %>
  </div>

  <div>
    <%= form.label :user_email, style: "display: block" %>
    <%= form.text_field :user_email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/time_messages/_time_message.html.erb
<div id="<%= dom_id time_message %>">
  <p>
    <strong>Content:</strong>
    <%= time_message.content %>
  </p>

  <p>
    <strong>Datetoopen:</strong>
    <%= time_message.dateToOpen %>
  </p>

  <p>
    <strong>User:</strong>
    <%= time_message.user_email %>
  </p>

</div>

app/views/time_messages/edit.html.erb
<h1>Editing time message</h1>

<%= render "form", time_message: @time_message %>

<br>

<div>
  <%= link_to "Show this time message", @time_message %> |
  <%= link_to "Back to time messages", time_messages_path %>
</div>

app/views/time_messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Time messages</h1>

<div id="time_messages">
  <% @time_messages.each do |time_message| %>
    <%= render time_message %>
    <p>
      <%= link_to "Show this time message", time_message %>
    </p>
  <% end %>
</div>

<%= link_to "New time message", new_time_message_path %>

app/views/time_messages/new.html.erb
<h1>New time message</h1>

<%= render "form", time_message: @time_message %>

<br>

<div>
  <%= link_to "Back to time messages", time_messages_path %>
</div>

app/views/time_messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @time_message %>

<div>
  <%= link_to "Edit this time message", edit_time_message_path(@time_message) %> |
  <%= link_to "Back to time messages", time_messages_path %>

  <%= button_to "Destroy this time message", @time_message, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>